import os

# Transcode constants
OVERWRITE_TRANSCODE_OUTPUT = os.getenv("OVERWRITE_TRANSCODE_OUTPUT", "False") == "True"
RECURSIVE_SLEEP_REQUEST = 5
MAX_MUXING_QUEUE_SIZE = 9999
MAX_FAIL_RETRY = 3
HLS_TIME = 5
HLS_LIST_SIZE = 10
DEFAULT_NEW_FILENAME = "index.m3u8"
HLS_NEW_FILENAME = "index.m3u8"
DASH_NEW_FILENAME = "index.mpd"
