site_name: Nucleus
site_description: The building block for decentralized media
site_url: https://synapsemedia.io/
repo_url: https://github.com/SynapseMedia/nucleus

nav:
  - Getting started: index.md
  - Usage guide: 
    - Harvesting raw: guide/harvest.md
    - Processing multimedia: guide/processing.md
    - Multimedia storage: guide/storage.md
    # - Publishing the metadata: index.md
    - Putting all together: guide/example.md
  - API Reference: 
    - Harvest:
        - Models: reference/harvest/models.md
        - Media: reference/harvest/media.md
        - Utilities: reference/harvest/utilities.md
        - Types: reference/harvest/types.md
    - Processing:
        - Engines: reference/processing/engines.md
        - Video: 
            - Settings: reference/processing/video/settings.md
            - Codecs: reference/processing/video/codecs.md
            - Protocols: reference/processing/video/protocols.md
            - Types: reference/processing/video/types.md
        - Image: 
            - Settings: reference/processing/image/settings.md
        - Utilities: reference/processing/utilities.md
        - Types: reference/processing/types.md
    - Storage:
        - Services: reference/storage/services.md
        - Utilities: reference/storage/utilities.md
        - Types: reference/storage/types.md
    - Exceptions: reference/exceptions.md
    
    # more here
  - Developer Guide:
    - Overview: dev/index.md
    - Architecture: dev/arch.md
    # - Metadata Standard
    # - Extending Media Types: dev/arch.md
    # - Extending Engines: dev/arch.md
    # - Extending Clients and Services: dev/arch.md
    # - Release notes: dev/arch.md


extra:
  analytics:
    provider: google
    property: G-9V6M4NPR7F

theme: 
  name: material
  # Palette toggle for light mode
  palette: 
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - include-markdown
  - search
  - glightbox
  - mkdocstrings:
      handlers:
        python:
          paths: [nucleus] # search packages in the src folder
          allow_inspection: true
          annotations_path: source


markdown_extensions:
- admonition
- pymdownx.highlight
- pymdownx.snippets
- pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
- attr_list
- md_in_html
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

