name: CI

on:
  push:
    branches:
      - 'master'
      - 'v0.*.0'
  pull_request:

jobs:
  cache-virtualenv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        id: cache-virtualenv

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('requirements.txt') }}

      - name: Install requirements
        run: |
          pip install -r requirements.txt

  static:
    needs: cache-virtualenv
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2

      - run: flake8 --config=.config/flake8.ini src
      - run: black --check --diff src

  tests:
    needs: cache-virtualenv
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
      - run: py.test -c ./conftest.py --no-header -v --disable-pytest-warnings

