name: CI

on:
  push:
    branches:
      - 'master'
      - 'v0.*.0'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.9 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2

      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements.txt

      - name: Static Analysis
        run: |
          flake8 --config=.config/flake8.ini src
      - name: Tests
        run: |
          py.test -c ./conftest.py --no-header -v --disable-pytest-warnings
