name: CI

on:
  push:
    branches:
      - 'master'
      - 'v0.*.0'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8, 3.9, 3.10 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

#      - uses: actions/cache@v2
#        id: cache
#        with:
#          path: ~/.cache/pip
#          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
#          restore-keys: |
#            ${{ runner.os }}-pip-

      - name: Install virtualenv
#        if: steps.cache.outputs.cache-hit != 'true'
        run: pip3 install virtualenv

      - name: Boostrap
#        if: steps.cache.outputs.cache-hit != 'true'
        run: make bootstrap

      - name: pytypes checker
        uses: theahura/pytypes-action@main

      - name: Static Analysis
        run: make check-coding-style

      - name: Tests
        run: |
          make test
