name: Codeball
on:
  pull_request: {}
  pull_request_review_comment:
    types: [created, edited]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  codeball:
    runs-on: ubuntu-latest
    name: Codeball
    steps:
      - name: Codeball
        uses: sturdy-dev/codeball-action@v2
        with:
          # For all configuration options see https://github.com/sturdy-dev/codeball-action/blob/v2/action.yml
          approvePullRequests: "true"
          labelPullRequestsWhenApproved: "true"
          labelPullRequestsWhenReviewNeeded: "false"
          failJobsWhenReviewNeeded: "false"

      # If Codeball have code suggestions, add suggestions as comments
      - name: Add Suggestions
        uses: sturdy-dev/codeball-action/suggester@v2
        if: ${{ steps.codeball_status.outputs.suggested == 'true' && inputs.codeSuggestionsFromComments == 'true' && steps.codeball_status.outputs.jobType == 'comment' }}
        with:
          codeball-job-id: ${{ steps.codeball_baller.outputs.codeball-job-id }}
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
